### ISSUE TITLE
ReferenceError: Regexp is not defined

### ISSUE THREAD

**Issue by danieladarve** [patrickcurl/laravel-mix-eslint-config#2]
There is a typo on index.js line 38
``? (Regexp(RegExp(`\\.(${config.test.join('|')})$`)))``
Should be
``? (RegExp(`\\.(${config.test.join('|')})$`))``

**Comment by joaopjt** [comment]
Fixed on my pull request, #3

**Comment by danieladarve** [comment]
Thank you @joaopjt
